const phone='5521970602683';
document.getElementById('year')?.append(new Date().getFullYear());
const menuBtn=document.querySelector('.menu-btn'); const header=document.querySelector('.header');
menuBtn?.addEventListener('click',()=>header.classList.toggle('nav-open'));
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>header.classList.remove('nav-open')));
const form=document.getElementById('whatsapp-form');
form?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const msg=`Olá, Luciano! Gostaria de solicitar um orçamento pela Serrana Pinturas & Reformas.%0A%0A*Nome:* ${encodeURIComponent(d.get('nome'))}%0A*WhatsApp:* ${encodeURIComponent(d.get('telefone'))}%0A*Serviço:* ${encodeURIComponent(d.get('servico'))}%0A*Projeto:* ${encodeURIComponent(d.get('mensagem'))}`;window.open(`https://wa.me/${phone}?text=${msg}`,'_blank','noopener');});
const gallery=document.getElementById('gallery');
if(gallery){const items=[['g1.png','pintura'],['g2.png','reforma'],['g3.png','pintura'],['g4.png','reforma'],['g5.png','pintura'],['g6.png','reforma'],['g7.png','pintura'],['g8.jpg','reforma']];gallery.innerHTML=items.map((x,i)=>`<figure data-category="${x[1]}" data-index="${i}"><img loading="lazy" src="assets/gallery/${x[0]}" alt="Obra Serrana ${i+1}"><figcaption>${x[1]==='pintura'?'Pintura e renovação':'Reforma e transformação'} • Projeto ${i+1}</figcaption></figure>`).join('');let current=0;const lb=document.getElementById('lightbox'),lbImg=lb.querySelector('img'),lbP=lb.querySelector('p');function open(i){current=i;lbImg.src=`assets/gallery/${items[i][0]}`;lbP.textContent=`Projeto ${i+1} de ${items.length}`;lb.classList.add('open');document.body.style.overflow='hidden'}function close(){lb.classList.remove('open');document.body.style.overflow=''}gallery.addEventListener('click',e=>{const f=e.target.closest('figure');if(f)open(+f.dataset.index)});lb.querySelector('.close').onclick=close;lb.onclick=e=>{if(e.target===lb)close()};lb.querySelector('.prev').onclick=()=>open((current-1+items.length)%items.length);lb.querySelector('.next').onclick=()=>open((current+1)%items.length);document.addEventListener('keydown',e=>{if(!lb.classList.contains('open'))return;if(e.key==='Escape')close();if(e.key==='ArrowLeft')open((current-1+items.length)%items.length);if(e.key==='ArrowRight')open((current+1)%items.length)});document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');document.querySelectorAll('.gallery figure').forEach(f=>f.style.display=b.dataset.filter==='all'||f.dataset.category===b.dataset.filter?'block':'none')});}
