const $=id=>document.getElementById(id);let allMedia=[];let currentFilter='all';
async function api(url,opts={}){const r=await fetch(url,{credentials:'same-origin',...opts});let d={};try{d=await r.json()}catch{};if(r.status===401)throw new Error('UNAUTHORIZED');if(!r.ok)throw new Error(d.erro||'Falha na operação');return d}
function msg(el,text,type=''){el.textContent=text;el.className='admin-msg '+type}
function setLoggedIn(user){$('login-panel').classList.add('hidden');$('dashboard-panel').classList.remove('hidden');$('btn-logout').classList.remove('hidden');$('admin-user').textContent=`Olá, ${user}`}
function setLoggedOut(){location.reload()}
async function check(){try{const d=await api('/api/admin/me');setLoggedIn(d.user);await loadMedia()}catch{}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user:$('login-user').value,password:$('login-password').value})});setLoggedIn(d.user);await loadMedia()}catch(err){msg($('login-msg'),err.message,'error')}});
$('btn-logout').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST'});setLoggedOut()});
document.querySelectorAll('.source-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.source-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const source=b.dataset.source;$('media-source').value=source;$('file-fields').classList.toggle('hidden',source!=='file');$('url-fields').classList.toggle('hidden',source!=='url');$('media-submit').textContent='Adicionar ao portfólio'}));
document.querySelectorAll('.media-filters button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.media-filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderMedia()}));
$('btn-refresh').addEventListener('click',loadMedia);
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function preview(m){if(m.type==='video'){if(/youtube\.com|youtu\.be|vimeo\.com/i.test(m.url)){return `<div class="media-preview"><div style="font-size:42px">▶</div></div>`}return `<div class="media-preview"><video src="${esc(m.url)}" muted controls preload="metadata"></video></div>`}return `<div class="media-preview"><img src="${esc(m.url)}" alt="" loading="lazy" onerror="this.style.opacity=.3"></div>`}
function renderMedia(){const list=$('media-list');const data=allMedia.filter(m=>currentFilter==='all'||m.type===currentFilter);if(!data.length){list.innerHTML='<p style="color:#999">Nenhuma mídia cadastrada.</p>';return}list.innerHTML=data.map(m=>`<article class="media-card">${preview(m)}<div class="media-info"><strong>${esc(m.title)}</strong><small>${m.type==='image'?'Foto':'Vídeo'} • ${esc(m.category)} • ${esc(m.source)}</small>${m.featured?'<span class="badge">DESTAQUE</span>':''}<div class="media-actions"><button class="admin-btn" data-edit="${m.id}">Editar</button><button class="admin-btn danger" data-delete="${m.id}">Excluir</button></div></div></article>`).join('');list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteMedia(b.dataset.delete));list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editMedia(b.dataset.edit))}
async function loadMedia(){try{const d=await api('/api/media');allMedia=d.media||[];$('stat-total').textContent=allMedia.length;$('stat-images').textContent=allMedia.filter(x=>x.type==='image').length;$('stat-videos').textContent=allMedia.filter(x=>x.type==='video').length;renderMedia()}catch(err){if(err.message==='UNAUTHORIZED')return msg($('media-msg'),'Sua sessão expirou. Entre novamente.','error');msg($('media-msg'),err.message,'error')}}
$('media-form').addEventListener('submit',async e=>{e.preventDefault();const id=$('media-id').value,source=$('media-source').value;try{if(id){const d=await api('/api/admin/media/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('media-title').value,category:$('media-category').value,description:$('media-description').value,featured:$('media-featured').checked})});msg($('media-msg'),'Mídia atualizada com sucesso.','success')}else if(source==='file'){const f=$('media-file').files[0];if(!f)throw new Error('Selecione um arquivo.');const fd=new FormData();fd.append('arquivo',f);fd.append('title',$('media-title').value);fd.append('category',$('media-category').value);fd.append('description',$('media-description').value);fd.append('featured',$('media-featured').checked);await api('/api/admin/media/upload',{method:'POST',body:fd});msg($('media-msg'),'Arquivo enviado com sucesso.','success')}else{await api('/api/admin/media/url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:$('media-url-type').value,url:$('media-url').value,thumbnailUrl:$('media-thumb').value,title:$('media-title').value,category:$('media-category').value,description:$('media-description').value,featured:$('media-featured').checked})});msg($('media-msg'),'Mídia por URL adicionada com sucesso.','success')}resetForm();await loadMedia()}catch(err){if(err.message==='UNAUTHORIZED')return msg($('media-msg'),'Sessão expirada. Recarregue a página e entre novamente.','error');msg($('media-msg'),err.message,'error')}});
function resetForm(){ $('media-id').value='';$('media-title').value='';$('media-description').value='';$('media-file').value='';$('media-url').value='';$('media-thumb').value='';$('media-featured').checked=false;$('media-cancel').classList.add('hidden');$('media-submit').textContent='Adicionar ao portfólio';}
function editMedia(id){const m=allMedia.find(x=>x.id===id);if(!m)return;$('media-id').value=m.id;$('media-title').value=m.title||'';$('media-category').value=m.category||'geral';$('media-description').value=m.description||'';$('media-featured').checked=!!m.featured;$('media-source').value='file';document.querySelectorAll('.source-tab').forEach(x=>x.classList.toggle('active',x.dataset.source==='file'));$('file-fields').classList.remove('hidden');$('url-fields').classList.add('hidden');$('media-submit').textContent='Salvar alterações';$('media-cancel').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
$('media-cancel').addEventListener('click',resetForm);
async function deleteMedia(id){const m=allMedia.find(x=>x.id===id);if(!m||!confirm(`Excluir "${m.title}"?\n\nEsta ação remove a mídia do portfólio. Arquivos enviados ao servidor também serão apagados.`))return;try{await api('/api/admin/media/'+id,{method:'DELETE'});msg($('media-msg'),'Mídia excluída com sucesso.','success');await loadMedia()}catch(err){msg($('media-msg'),err.message,'error')}}
check();
